### ISSUE TITLE
Color Temp for Lights

### ISSUE THREAD

**Issue by csmyrnos** [TheOneOgre/govee-cloud#23]
First off, thank you for this integration! I bought a few inexpensive Govee light bulbs (H6004) from Best Buy and this integration has made it easy to control them via Home Assistant, whereas they’re not compatible with the main Govee integrations.

One thing I was hoping for is the ability to control the light temperature. For example, with the current Hue integration, I am able to select the normal light colors, but there is also a temperature slider (cool white -> warm white). Is it possible for that to be exposed via this plugin? I know these lights support this feature because I can set this via the Govee app. Would be great if this could also be set in HA.

Current controls:

<img width="816" height="1095" alt="Image" src="https://github.com/user-attachments/assets/7d0825d4-a8f1-4818-a2ab-7a80c16e7f12" />

Requested controls:

<img width="1187" height="1451" alt="Image" src="https://github.com/user-attachments/assets/ce953671-0eff-4118-8da2-8e14a05365e4" />

Thanks!

**Comment by TheOneOgre** [comment]
I have checked that model and it seems to not use the standard colortem or colorkelvin values, but some new ones govee uses.
I've updated the color temperature detection that "unlocks" the temperature selector to scan for these values, so it should now work for your model. If it does not, I'll work with you to grab a list of supportedCMD's for your specific models and add commands static for that model. 

Thanks for the report, this is very similar to the issues being reported in #13 but I'll keep them separate for now. Please try [v0.3.3.1-TheBigFix](https://github.com/TheOneOgre/govee-cloud/releases/tag/v0.3.3.1-TheBigFix)

**Comment by csmyrnos** [comment]
Thanks for taking a look. I installed 0.3.3.1 but the color temp is still not exposed in Home Assistant. Let me know what data I can grab to help out. ChrisOn Sep 21, 2025, at 8:22 PM, TheOgre ***@***.***> wrote:﻿TheOneOgre left a comment (TheOneOgre/govee-cloud#23)
I have checked that model and it seems to not use the standard colortem or colorkelvin values, but some new ones govee uses.
I've updated the color temperature detection that "unlocks" the temperature selector to scan for these values, so it should now work for your model. If it does not, I'll work with you to grab a list of supportedCMD's for your specific models and add commands static for that model.
Thanks for the report, this is very similar to the issues being reported in #13 but I'll keep them separate for now. Please try v0.3.3.1-TheBigFix

**Comment by TheOneOgre** [comment]
> Thanks for taking a look. I installed 0.3.3.1 but the color temp is still not exposed in Home Assistant. Let me know what data I can grab to help out.
> 
> Chris

Alright so I figured out from my own testing, that Govee seems to have changed their mobileapi and it wasn't even reporting color temperature, which I was previously relying on to determine if the device supported it. I've updated the detection logic and it should actually be working now haha. 

If not, I've added raw payloads to the debug logs, so if you're still experiencing it, enable debug logs for Govee, restart home assistant, then disable debug logging and upload the logs here.


Please try [v0.3.3.2-TheBigFix](https://github.com/TheOneOgre/govee-cloud/releases/tag/v0.3.3.2-TheBigFix)

**Comment by csmyrnos** [comment]
This worked, thanks. The color temp is now exposed in HA. Only issue I ran into was I initially tried to update in HACS by selecting this version. After the update/restart, my entities and the integration were unavailable. I had to remove the integration and the HACS download. I reinstalled everything from scratch and it’s working fine now. Thanks again.
